staging-settings:
  user-workflow:
    workflow-name: 'proof-of-reserve-staging'
  workflow-artifacts:
    workflow-path: './index.ts'
    config-path: './config.staging.json'
    secrets-path: ''

production-settings:
  user-workflow:
    workflow-name: 'proof-of-reserve-production'
  workflow-artifacts:
    workflow-path: './index.ts'
    config-path: './config.production.json'
    secrets-path: ''