staging-settings:
  user-workflow:
    workflow-name: 'lifecycle-reconcile-staging'
  workflow-artifacts:
    workflow-path: './index.ts'
    config-path: './config.staging.json'
    secrets-path: ''

production-settings:
  user-workflow:
    workflow-name: 'lifecycle-reconcile-production'
  workflow-artifacts:
    workflow-path: './index.ts'
    config-path: './config.production.json'
    secrets-path: ''